version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "13306:3306"
    volumes:
      # 永続データ
      # .data/dbは起動時に自動生成される
      - ./.data/db:/var/lib/mysql

      # 起動時のデータ初期化
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
